Fix container build, version and readme update

diff --git a/Dockerfile.x86 b/Dockerfile.x86
--- a/Dockerfile.x86
+++ b/Dockerfile.x86
@@ -35,25 +35,6 @@ RUN \
 
 FROM ghcr.io/linuxserver/baseimage-kasmvnc:debianbookworm-9d98b2d5-ls120 AS buildstage
 
-WORKDIR /opt
-
-ARG BISQ_VERSION=1.9.21
-ENV BISQ_DEBFILE=Bisq-64bit-$BISQ_VERSION.deb
-ENV BISQ_DEB_URL=https://bisq.network/downloads/v$BISQ_VERSION/$BISQ_DEBFILE
-ENV BISQ_ASC_URL=https://bisq.network/downloads/v$BISQ_VERSION/$BISQ_DEBFILE.asc
-# signing key (Alejandro García)
-ENV BISQ_PGP_KEY=B493319106CC3D1F252E19CBF806F422E222AA02
-
-# Install Bisq
-RUN mkdir bisq-install && cd bisq-install; \
-  wget -qO $BISQ_DEBFILE "$BISQ_DEB_URL"; \
-  gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "$BISQ_PGP_KEY"; \
-  wget -qO "$BISQ_DEBFILE".asc "$BISQ_ASC_URL"; \
-  gpg --digest-algo SHA256 --verify "$BISQ_DEBFILE".asc; \
-  cd .. || echo "WARNING: Bisq Installation Failed."
-RUN dpkg -i /opt/bisq-install/$BISQ_DEBFILE; \
-  rm -rf /opt/bisq-install
-
 RUN \
   echo "**** install packages ****" && \
   apt-get update && \
@@ -83,8 +64,29 @@ RUN \
   # other
   wget \
   socat \
-  gnupg && \
-  # remove unused packages from base image
+  gnupg
+
+# Install Bisq
+WORKDIR /opt
+
+ARG BISQ_VERSION=1.9.21
+ENV BISQ_DEBFILE=Bisq-64bit-$BISQ_VERSION.deb
+ENV BISQ_DEB_URL=https://bisq.network/downloads/v$BISQ_VERSION/$BISQ_DEBFILE
+ENV BISQ_ASC_URL=https://bisq.network/downloads/v$BISQ_VERSION/$BISQ_DEBFILE.asc
+# signing key (Alejandro García)
+ENV BISQ_PGP_KEY=B493319106CC3D1F252E19CBF806F422E222AA02
+
+RUN mkdir bisq-install && cd bisq-install; \
+  wget -qO $BISQ_DEBFILE "$BISQ_DEB_URL"; \
+  gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "$BISQ_PGP_KEY"; \
+  wget -qO "$BISQ_DEBFILE".asc "$BISQ_ASC_URL"; \
+  gpg --digest-algo SHA256 --verify "$BISQ_DEBFILE".asc; \
+  cd .. || echo "WARNING: Bisq Installation Failed."
+RUN dpkg -i /opt/bisq-install/$BISQ_DEBFILE; \
+  rm -rf /opt/bisq-install  
+
+# remove unused packages from base image
+RUN \
   DEBIAN_FRONTEND=noninteractive \
   apt-get remove --purge --autoremove -y \
   containerd.io \
